# Generated by Django 6.1.1 on 2026-09-09 13:49

import apps.tables.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('qr_token', models.CharField(db_index=True, default=apps.tables.models.generate_qr_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='branches.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'number'), name='uniq_table_number_per_branch')],
            },
        ),
    ]
