# Generated by Django 6.1.1 on 2026-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_category_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='template_name',
            field=models.CharField(blank=True, default='classic', max_length=50),
        ),
    ]
