# Generated by Django 6.1.1 on 2026-09-07 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_seed_roles_and_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-rank', 'name']},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'tenant'], name='tenants_mem_user_id_f01927_idx'),
        ),
    ]
