# Generated by Django 6.1.1 on 2026-09-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('tenants', '0003_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='branches.branch'),
        ),
    ]
